name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npx jest

    - name: Build project
      run: npm run build

    - name: Verify build files
      run: |
        echo "Contents of dist folder:"
        ls -la dist/
        [ -f dist/index.html ] && echo "✓ index.html exists" || echo "✗ index.html missing"
        [ -f dist/bundle.js ] && echo "✓ bundle.js exists" || echo "✗ bundle.js missing"
        [ -f dist/styles.css ] && echo "✓ styles.css exists" || echo "✗ styles.css missing"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist